/* automatically generated by rust-bindgen */

pub const WEBSOCAT_API_VERSION: ::std::os::raw::c_int = 0;
pub type websocat_api_version =
    ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>;
pub type websocat_create_regular_sync = ::std::option::Option<
    unsafe extern "C" fn(restcmdline: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_void,
>;
pub type websocat_destroy_regular_sync =
    ::std::option::Option<unsafe extern "C" fn(endpoint: *mut ::std::os::raw::c_void)>;
pub type websocat_sync_read = ::std::option::Option<
    unsafe extern "C" fn(
        endpoint: *mut ::std::os::raw::c_void,
        buf: *mut ::std::os::raw::c_void,
        buflen: usize,
    ) -> usize,
>;
pub type websocat_sync_write = ::std::option::Option<
    unsafe extern "C" fn(
        endpoint: *mut ::std::os::raw::c_void,
        buf: *const ::std::os::raw::c_void,
        buflen: usize,
    ) -> usize,
>;
